const { cmd } = require('../command');
const axios = require('axios');

const commandName = 'media';
const apiUrl = 'https://pikabotzapi.vercel.app/';

cmd({
    'pattern': 'media',
    'alias': ['randommedia'],
    'desc': 'Get random media based on keywords',
    'category': 'media',
    'use': '.media <keyword>',
    'filename': __filename
}, async (m, sock, msg, { args, reply }) => {
    try {
        const keyword = args[0] || 'random';
        const mediaTypes = [
            `${apiUrl}random/image/?apikey=anya-md&query=${keyword}`,
            `${apiUrl}random/video/?apikey=anya-md&query=${keyword}`,
            `${apiUrl}random/gif/?apikey=anya-md&query=${keyword}`
        ];
        
        const reactions = ['❤️', '😂', '😍', '🔥', '👍', '🎉', '🤩'];
        const randomReaction = reactions[Math.floor(Math.random() * reactions.length)];
        const randomMedia = mediaTypes[Math.floor(Math.random() * mediaTypes.length)];
        
        await m.sendMessage(msg.remoteJid, {
            'react': {
                'text': randomReaction,
                'key': msg.key
            }
        });
        
        const response = await axios.get(randomMedia);
        
        if (response.data.status && response.data.url) {
            const mediaUrl = response.data.url;
            const caption = `🎬 *Random Media:* ${keyword}\n\n> *© Generated By MASTERTECH-XD V2*`;
            
            await m.sendMessage(msg.remoteJid, {
                'video': { 'url': mediaUrl },
                'caption': caption,
                'contextInfo': {
                    'mentionedJid': [msg.sender],
                    'forwardingScore': 999,
                    'isForwarded': false,
                    'externalAdReply': {
                        'title': 'Random Media',
                        'body': 'Powered by PikaBotz API',
                        'mediaType': 1
                    }
                }
            }, { 'quoted': sock });
            
            await m.sendMessage(msg.remoteJid, {
                'text': 'Enjoy your media! 🎉',
                'mentions': []
            }, { 'quoted': sock });
        } else {
            reply('❌ Failed to fetch media for "' + keyword + '".');
        }
    } catch (error) {
        console.error('Error:', error);
        await m.sendMessage(msg.remoteJid, {
            'text': `❌ Error: ${error.message}`
        }, { 'quoted': sock });
    }
});