const { cmd, commands } = require('../command');
const { getBuffer, getGroupAdmins, getRandom, h2k, isUrl, Json, runtime, sleep, fetchJson } = require('../lib/functions');
const axios = require('axios');

function hi() {
    console.log('Hello World!');
}
hi();

cmd({
    'pattern': 'rw',
    'alias': ['wallpaper', 'randomwall'],
    'react': '🌌',
    'desc': 'Download random wallpapers based on keywords.',
    'category': 'wallpapers',
    'use': '.rw <keyword>',
    'filename': __filename
}, async (m, sock, msg, { from, args, reply }) => {
    try {
        const query = args.join(' ') || 'random';
        const apiUrl = 'https://pikabotzapi.vercel.app/random/randomwall/?apikey=anya-md&query=' + query;
        const response = await axios.get(apiUrl);
        
        if (response.data.status) {
            const imgUrl = response.data.imgUrl;
            const caption = '🌌 Random Wallpaper: *' + query + '*\n\n> *© Generated By INCONNU-XD*';
            
            await m.sendMessage(from, {
                'image': { 'url': imgUrl },
                'caption': caption
            }, { 'quoted': sock });
        } else {
            reply('❌ Failed to fetch wallpaper for "' + query + '".');
        }
    } catch (error) {
        console.error(error);
        reply('❌ An error occurred while fetching the wallpaper.');
    }
});